### PR TITLE
complete theme injection

### PR DESCRIPTION
**Pull request by nandorojo**
@hasparus is this the right approach to adding more scales here?

Note, I haven't added any comments yet, but if this is the right path, then I could do that next.

cc @cmaycumber

PS I have this set to merge into @hasparus's branch, not sure if that's the right move or not. I haven't done a PR pointed at another PR before.

### CODE REVIEW

**Comment by hasparus** [comment]
> @hasparus is this the right approach to adding more scales here?

If it works for you. Or actually, I could move my branch to theme-ui repo to keep all conversation there.

**Comment by hasparus** [comment]
BTW. All CSS object properties are optional (`:?`) I noticed in the CI failure.

**Comment by hasparus** [comment]
> Or actually, I could move my branch to theme-ui repo to keep all conversation there.

@nandorojo, it's impossible to change base branch of the PR. Let's keep it here, I'll try to merge anything swiftly so we can still be focused on system-ui/theme-ui repo and use this branch just to consolidate the code.

**Comment by nandorojo** [comment]
@hasparus Looks like my tests are failing in the `css` package still. I'm doing this a bit brute-force since I'm not super familiar with the code base, but I believe I've followed your work so far with the colors. 

Does anything stand out to you as the reason for the errors here so far?

**Comment by hasparus** [comment]
I think we can merge it with failing tests. I'll take a look at them tonight.

**Comment by hasparus** [comment]
I'm giving you access to this fork so you can merge whenever you're ready.

**Comment by nandorojo** [comment]
> I think we can merge it with failing tests. I'll take a look at them tonight.

Appreciate that, thanks!

**Pull request merged**
